name: CI
on:
  pull_request:
    branches: [main, staging]
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.10.0]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node dependencies
        run: yarn install
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Initialize amplify_outputs.json
        run: |
          echo "{}" > amplify_outputs.json
      - name: Run Build
        run: yarn build
